config/routes.rb
Rails.application.routes.draw do
  resources :products

  devise_for :users

  get 'step_one' => 'purchases#index', as: :step_one
  post 'step_one/purchases' => 'purchases#purchase'

  get 'step_two' => 'purchases#step_two', as: :step_two
  post 'step_two/purchases' => 'purchases#create'

  get 'home/index'

  root 'purchases#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :purchased_products
  has_many :purchases, through: :purchased_products
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  has_many :purchased_products
  has_many :products, through: :purchased_products
  belongs_to :user

  # add products to the purchase
  def add_products!(products)
    processing_errors = []

    Purchase.transaction do
      products.each do |product|
        entry = PurchaseEntry.new(product)
        if(entry.valid?)
          begin
            self.add_product!(entry.product_id, entry.quantity)

          rescue Exception => e
            processing_errors = [{error: e.message}]
          end
        else
          processing_errors = entry.errors
        end

        break if(processing_errors.length > 0)
      end

      unless(processing_errors.length > 0)
        self.save!
      end
    end

    return processing_errors
  end

  # add a single product to the purchase and update the quantity
  def add_product!(product_id, quantity)
    product = Product.find product_id
    
    if(product.stock >= quantity)
      product.stock -= quantity
      if(product.save!)
        purchased_product = PurchasedProduct.new(product_id: product_id, quantity: quantity)
        self.purchased_products << purchased_product
      end
    else
      raise "There are only #{product.stock} products in stock and #{quantity} were requested"
    end
  end

  # show json of records involved in purchase
  def prepare_response
      json = JSON.parse(self.to_json)
      Product.joins{purchased_products}.where{(purchased_products.purchase_id == my{self.id})}.select{[id, name, stock, purchased_products.quantity]}
      json["products"] = JSON.parse(self.products.to_json)
      json
  end
end

app/models/purchase_entry.rb
class PurchaseEntry
  include ActiveModel::Validations

  attr_accessor :product_id, :quantity

  validates :product_id, :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def initialize(attrs={})
    @product_id = attrs[:id].to_i
    @quantity = attrs[:quantity].to_i
  end
end

app/models/purchased_product.rb
class PurchasedProduct < ActiveRecord::Base
  belongs_to :purchase
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :purchases
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authorize(record)
    raise Errors::NotAuthorizedError unless policy(record).public_send(params[:action] + "?")
  end

  def policy(record)
    "#{record.class}Policy".constantize.new(current_user, record)
  end  

  rescue_from Errors::NotAuthorizedError do
    render text: "Access Denied", status: :unauthorized
  end  

  rescue_from Exception do
    render text: "Server Error", status: 500
  end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_user!, only: [:step_two, :create]

  # override ApplicationController exception handling since we only want json returned for
  # #purchase and #create
  rescue_from Exception do
    render json: JSON.generate({message: "Server error"}), status: 500
  end  

  rescue_from Errors::NotAuthorizedError do
    render json: JSON.generate({message: "Access Denied"}), status: :unauthorized
  end  
  
  
  def index
  end

  def step_two
    @products = Product.all
  end

  def purchase
    # give a little time to show the update to the button in the view
    sleep(1)

    if(params.has_key? "error")
      render json: JSON.generate({message: "there's been an error"}), status: 400
    else
      render json: JSON.generate({message: "Thanks for your purchase"})
    end
  end

  def create
    processing_errors = []
    @purchase = Purchase.new()
    @purchase.user = current_user

    authorize(@purchase)
    processing_errors = @purchase.add_products!(products_params)

    respond_to do |format|
      if (processing_errors.length == 0)
        format.json { render json: @purchase.prepare_response, status: :created }
      else
        format.json { render json: processing_errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def products_params
      params.require(:products) do |product|
        product.permit(:id, :quantity)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yekra001</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="col-med-12 nav">
  <%= link_to "Step 1", step_one_path %> | <%= link_to "Step 2", step_two_path %>
</div>

<%= yield %>
</div>

</body>
</html>

app/views/purchases/create.html.erb
<h1>Purchases#create</h1>
<p>Find me in app/views/purchases/create.html.erb</p>

app/views/purchases/index.html.erb
<div class="container purchase_section">
  <div class="products">

    <div class="product">
    <label>Canon EFS 75-300</label>
    <input type="hidden" name="products[][id]" value="1"/>
    <input type="text" name="products[][quantity]" />
    </div>

    <div class="product">
    <label>Canon EFS 18-55</label>
    <input type="hidden" name="products[][id]" value="2"/>
    <input type="text" name="products[][quantity]" />
    </div>

    <div class="product">
    <label>Canon EFS 14mm</label>
    <input type="hidden" name="products[][id]" value="3"/>
    <input type="text" name="products[][quantity]" />
    </div>

    <div class="control">
    <%= label_tag :generate_error %>
    <%= check_box_tag :generate_error %>
    </div>
  </div>

  <div class="message"></div>

  <button class="purchase_btn">
    Purchase!
  </button>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $(".purchase_btn").on("click", function(event){
      event.preventDefault();

      var data = $(this).closest(".purchase_section").find(".products").find("input, textarea, select").serialize();

      // since it is required to trigger an error, we can do so manually
      var generate_error = ($(".products .control input[name='generate_error']:checked").length > 0) ? true : false;
      if(generate_error){
        data += "&error=true"
      }

      console.log(data);

      var button_text_orig = $(".purchase_btn").text();
      $(".message").removeClass("success, error")
      $(".purchase_btn").text("processing...");
      $(".message").text("");

      var jqxhr = $.post( "/step_one/purchases", data, function(response) {
        //alert( "success" );
      })
      .done(function(responseJSON) {
        var message = responseJSON["message"]
        //$(".message").addClass("success")
        $(".purchase_section").text(message);
        
        //alert( "second success" );
      })
      .fail(function(response) {
        console.log(response);
        var message = response.responseJSON["message"]
        $(".message").addClass("error")
        $(".message").text(message);

        //alert( "error" );
      })
      .always(function() {
        $(".purchase_btn").text(button_text_orig);

        //alert( "finished" );
      });
    });
  });
</script>

app/views/purchases/step_two.html.erb
<div class="purchase_section">
  <div class="products">

  <ul>
    <% @products.each do |product| %>
      <li><%= product.name %></li>
    <% end %>
  </ul>

  <div class="message">Given a POST request to:  PurchasesController#create
  with params { "products" => [  { "id" => 46, "quantity" => 3  }, {  "id" => 70, "quantity" => 2 } ] }</div>

  <button class="purchase_btn">
    Purchase!
  </button>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $(".purchase_btn").on("click", function(event){
      event.preventDefault();

      //var data = { products: [  { id: 46, quantity: 3  }, {  id: 70, quantity: 2 } ] };
      var data = "products%5B%5D%5Bid%5D=46&products%5B%5D%5Bquantity%5D=3&products%5B%5D%5Bid%5D=70&products%5B%5D%5Bquantity%5D=2"
      console.log(data);

      var button_text_orig = $(".purchase_btn").text();
      $(".message").removeClass("success, error")
      $(".purchase_btn").text("processing...");
      $(".message").text("");

      var jqxhr = $.post( "/step_two/purchases.json", data, function(response) {
        //alert( "success" );
      })
      .done(function(responseJSON) {
        var message = JSON.stringify(responseJSON)
        //$(".message").addClass("success")
        $(".purchase_section").text(message);
        
        //alert( "second success" );
      })
      .fail(function(response) {
        console.log(response);
        var message = response.responseJSON["message"]
        $(".message").addClass("error")
        $(".message").text(message);

        //alert( "error" );
      })
      .always(function() {
        $(".purchase_btn").text(button_text_orig);

        //alert( "finished" );
      });
    });
  });
</script>